version: '3.0'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/app
    container_name: ${PROJECT_NAME}-php-fpm
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.221.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/app
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - internal

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./app:/app
    command: sleep 10000
    container_name: ${PROJECT_NAME}-php-cli

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    ports:
      - "${MYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${PROJECT_NAME}-rabbitmq
    ports:
      - "${RABBITMQ_PORT_1}:5672"
      - "${RABBITMQ_PORT_2}:15672"
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28